package mirror

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// AndroidConfigurator Android SDK 镜像源配置器
type AndroidConfigurator struct {
	registry *Registry
}

// NewAndroidConfigurator 创建Android配置器
func NewAndroidConfigurator(registry *Registry) *AndroidConfigurator {
	return &AndroidConfigurator{registry: registry}
}

// Configure 配置Android SDK 镜像源
// 通过修改 ~/.android/repositories.cfg 和 ~/.gradle/init.d/ 下的 Gradle 初始化脚本
// 来实现 sdkmanager 与依赖下载走国内镜像源
func (a *AndroidConfigurator) Configure(mirror string) error {
	if mirror == "" {
		mirror = "aliyun"
	}

	url, ok := a.registry.GetMirror("android", mirror)
	if !ok {
		return fmt.Errorf("未找到镜像源: %s", mirror)
	}

	// 创建/修改 ~/.android/repositories.cfg
	if err := a.writeRepositoriesCfg(url); err != nil {
		return err
	}

	// 通过 Gradle init.d 配置 sdkmanager 走镜像源
	if err := a.writeGradleInitForAndroid(url); err != nil {
		return err
	}

	// 设置环境变量机制（写入 shell profile）
	if err := a.exportEnvVars(url); err != nil {
		return err
	}

	fmt.Printf("✓ 已配置Android SDK 镜像源: %s\n", url)
	return nil
}

// ConfigureGradle 配置全局 Gradle 镜像源（Android 场景）
// 等价于调用 GradleConfigurator.Configure，使用 aliyun 替换所有 maven 仓库
func (a *AndroidConfigurator) ConfigureGradle(mirror string) error {
	gradle := NewGradleConfigurator(a.registry)
	return gradle.Configure(mirror)
}

// ConfigureMaven 配置全局 Maven 镜像源（备用）
// 通过修改 ~/.m2/settings.xml 添加 mirror 配置
func (a *AndroidConfigurator) ConfigureMaven(mirror string) error {
	if mirror == "" {
		mirror = "aliyun"
	}

	url, ok := a.registry.GetMirror("maven", mirror)
	if !ok {
		return fmt.Errorf("未找到Maven镜像源: %s", mirror)
	}

	// 获取 Maven settings.xml 路径
	settingsPath, err := a.getMavenSettingsPath()
	if err != nil {
		return err
	}

	// 创建目录
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0755); err != nil {
		return fmt.Errorf("创建Maven配置目录失败: %w", err)
	}

	// 写入/覆盖 settings.xml
	content := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <mirrors>
        <mirror>
            <id>envkit-mirror</id>
            <name>envkit Maven Mirror</name>
            <url>%s</url>
            <mirrorOf>*</mirrorOf>
        </mirror>
    </mirrors>
</settings>
`, url)

	if err := os.WriteFile(settingsPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入Maven settings.xml 失败: %w", err)
	}

	fmt.Printf("✓ 已配置Maven镜像源: %s\n", url)
	fmt.Printf("  配置文件: %s\n", settingsPath)
	return nil
}

// Verify 验证配置是否生效（检查文件是否存在）
func (a *AndroidConfigurator) Verify() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	repositoriesCfg := filepath.Join(home, ".android", "repositories.cfg")
	if _, err := os.Stat(repositoriesCfg); os.IsNotExist(err) {
		return fmt.Errorf("repositories.cfg 不存在: %s", repositoriesCfg)
	}
	fmt.Printf("✓ repositories.cfg: %s\n", repositoriesCfg)

	// 检查 Gradle init.d 目录
	gradleInit := filepath.Join(home, ".gradle", "init.d", "aliyun.gradle")
	if _, err := os.Stat(gradleInit); os.IsNotExist(err) {
		return fmt.Errorf("Gradle init 脚本不存在: %s", gradleInit)
	}
	fmt.Printf("✓ Gradle init 脚本: %s\n", gradleInit)
	return nil
}

// writeRepositoriesCfg 创建/修改 ~/.android/repositories.cfg
// 该文件会被 sdkmanager 读取，作为仓库地址的来源
func (a *AndroidConfigurator) writeRepositoriesCfg(mirrorURL string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	androidDir := filepath.Join(home, ".android")
	if err := os.MkdirAll(androidDir, 0755); err != nil {
		return fmt.Errorf("创建 .android 目录失败: %w", err)
	}

	repositoriesCfg := filepath.Join(androidDir, "repositories.cfg")
	// 若文件已存在则保留（避免破坏用户原有内容），否则写入空配置
	if _, err := os.Stat(repositoriesCfg); os.IsNotExist(err) {
		content := fmt.Sprintf(`## This file is automatically generated by envkit.
## It contains the repositories that are recognized by Android SDK manager.
## Do not modify this file.
###
%v
`, mirrorURL)
		if err := os.WriteFile(repositoriesCfg, []byte(content), 0644); err != nil {
			return fmt.Errorf("写入 repositories.cfg 失败: %w", err)
		}
	}
	return nil
}

// writeGradleInitForAndroid 写入 ~/.gradle/init.d/android-mirror.gradle
// 让 sdkmanager 走国内镜像源（通过环境变量 ANDROID_USER_HOME 触发）
func (a *AndroidConfigurator) writeGradleInitForAndroid(mirrorURL string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	initDir := filepath.Join(home, ".gradle", "init.d")
	if err := os.MkdirAll(initDir, 0755); err != nil {
		return fmt.Errorf("创建 Gradle init.d 目录失败: %w", err)
	}

	initFile := filepath.Join(initDir, "android-mirror.gradle")
	content := fmt.Sprintf(`// 由 envkit 自动生成：Android SDK 国内镜像源
// 配合 ANDROID_USER_HOME 指向国内镜像
allprojects {
    buildscript {
        repositories {
            maven { url '%s' }
        }
    }
    repositories {
        maven { url '%s' }
    }
}
`, mirrorURL, mirrorURL)

	if err := os.WriteFile(initFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入 Gradle init 脚本失败: %w", err)
	}
	return nil
}

// exportEnvVars 将 USE_ANDROID_MIRROR / ANDROID_USER_HOME 写入 shell profile
func (a *AndroidConfigurator) exportEnvVars(mirrorURL string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	envLines := []string{
		"# Android SDK 镜像源（由 envkit 配置）",
		fmt.Sprintf("export USE_ANDROID_MIRROR=%s", mirrorURL),
		fmt.Sprintf("export ANDROID_USER_HOME=%s", filepath.Join(home, ".android")),
	}

	profiles := a.profilePaths(home)
	for _, p := range profiles {
		if _, err := os.Stat(p); err == nil {
			a.appendToFile(p, envLines)
		}
	}
	return nil
}

// getMavenSettingsPath 获取 Maven settings.xml 路径
func (a *AndroidConfigurator) getMavenSettingsPath() (string, error) {
	var settingsPath string
	switch runtime.GOOS {
	case "windows":
		userProfile := os.Getenv("USERPROFILE")
		if userProfile == "" {
			return "", fmt.Errorf("无法获取USERPROFILE环境变量")
		}
		settingsPath = filepath.Join(userProfile, ".m2", "settings.xml")
	case "darwin", "linux":
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("无法获取用户目录: %w", err)
		}
		settingsPath = filepath.Join(home, ".m2", "settings.xml")
	default:
		return "", fmt.Errorf("不支持的操作系统: %s", runtime.GOOS)
	}
	return settingsPath, nil
}

// profilePaths 返回当前平台常见的 shell profile 路径
func (a *AndroidConfigurator) profilePaths(home string) []string {
	switch runtime.GOOS {
	case "windows":
		// Windows 不走 shell profile，环境变量通过 setx 处理（此处留空）
		return nil
	case "darwin", "linux":
		return []string{
			filepath.Join(home, ".bashrc"),
			filepath.Join(home, ".zshrc"),
			filepath.Join(home, ".profile"),
		}
	}
	return nil
}

// appendToFile 追加内容到文件末尾
func (a *AndroidConfigurator) appendToFile(path string, lines []string) error {
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	for _, line := range lines {
		if _, err := f.WriteString(line + "\n"); err != nil {
			return err
		}
	}
	return nil
}
